name: 'Sentry User Feedback'
description: 'An action to monitor the Sentry User Feedback'
inputs:
  time-ms-period:  # id of input
    description: 'Time Period to check in miliseconds'
    required: true
    default: '300000'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'